# Generated by Django 5.0.1 on 2024-02-28 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_img',
            field=models.ImageField(blank=True, default='user_png.png', upload_to='profile_images'),
        ),
    ]
